// =============================================================================
// TPAC — Role → Permission mapping
// =============================================================================

import { PERMISSIONS, PermissionType } from "./permissions.js";
import { Role } from "./enums.js";

export const USER_ROLES = Role;
export type UserRoleType = Role;

export const ROLE_PERMISSIONS: Record<UserRoleType, PermissionType[]> = {

  [Role.SUPER_ADMIN]: [
    PERMISSIONS.ADD_ADMIN,
    PERMISSIONS.MANAGE_PLATFORM,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_FEATURE_FLAGS,
    PERMISSIONS.MANAGE_INTEGRATIONS,
  ],

  [Role.ADMIN]: [
    PERMISSIONS.MANAGE_COUNTRIES,
    PERMISSIONS.MANAGE_TIERS,
    PERMISSIONS.MANAGE_PRICING,
    PERMISSIONS.ADD_MANAGER,
    PERMISSIONS.VIEW_ALL_MEMBERS,
    PERMISSIONS.MANAGE_CORPORATE,
    PERMISSIONS.VIEW_REVENUE,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.BROADCAST_COMMS,
    // Admin can also do everything a Manager can
    PERMISSIONS.MANAGE_MEMBERS,
    PERMISSIONS.MANAGE_COMMUNITY,
    PERMISSIONS.MANAGE_PROGRAMMES,
    PERMISSIONS.MANAGE_COHORTS,
    PERMISSIONS.MANAGE_MENTORSHIP,
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.MANAGE_OPPORTUNITIES,
    PERMISSIONS.SEND_COMMS,
    PERMISSIONS.HANDLE_SUPPORT,
    PERMISSIONS.ASSIGN_MENTOR,
    PERMISSIONS.UPLOAD_CERTIFICATES,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],

  [Role.MANAGER]: [
    PERMISSIONS.MANAGE_MEMBERS,
    PERMISSIONS.MANAGE_COMMUNITY,
    PERMISSIONS.MANAGE_PROGRAMMES,
    PERMISSIONS.MANAGE_COHORTS,
    PERMISSIONS.MANAGE_MENTORSHIP,
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.MANAGE_OPPORTUNITIES,
    PERMISSIONS.SEND_COMMS,
    PERMISSIONS.HANDLE_SUPPORT,
    PERMISSIONS.ASSIGN_MENTOR,
    PERMISSIONS.UPLOAD_CERTIFICATES,
  ],

  [Role.CORPORATE_ADMIN]: [
    PERMISSIONS.MANAGE_ORG_TEAM,
    PERMISSIONS.VIEW_ORG_REPORTS,
    PERMISSIONS.MANAGE_ORG_BILLING,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.ACCESS_EVENTS,
  ],

  [Role.MENTOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_MENTEES,
    PERMISSIONS.MANAGE_SESSIONS,
    PERMISSIONS.VIEW_COHORT_BRIEFS,
    PERMISSIONS.ACCESS_COMMUNITY,
    PERMISSIONS.ACCESS_LEARN,
    PERMISSIONS.ACCESS_OPPORTUNITIES,
    PERMISSIONS.ACCESS_EVENTS,
  ],

  [Role.MEMBER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.ACCESS_EVENTS,  // public events only at EXPLORER tier — gated further by tier in service layer
    PERMISSIONS.ACCESS_LEARN,   // 1 course/month at EXPLORER — gated by MemberProfile.coursesUsedThisMonth
  ],
};

export const hasPermission = (
  role: UserRoleType,
  permission: PermissionType,
): boolean => (ROLE_PERMISSIONS[role] ?? []).includes(permission);
